= ovirt-engine-nodejs-modules

== Summary

This package contains the dependencies needed to build oVirt JavaScript
applications.

== Usage

Modify your build script and/or CI job configuration to ensure following
packages are installed when building your project:

* `ovirt-engine-nodejs`
* `ovirt-engine-nodejs-modules`
* `ovirt-engine-yarn`

It's highly recommended to specify an explicit `Version-Release` when
requiring the `ovirt-engine-nodejs-modules` package in your project.

For example, in your `automation/build-artifacts.packages` file:

  ovirt-engine-nodejs-modules-1.2.3

=== Build script

In your build script, source `setup-env.sh` to set up Node.js environment
and populate the `./node_modules` directory:

 cd /path/to/your/project
 source /usr/share/ovirt-engine-nodejs-modules/setup-env.sh

The setup script runs `yarn install` in offline mode, using JavaScript
package sources located at:

 /usr/share/ovirt-engine-nodejs-modules/yarn-offline-cache

If the above mentioned command fails, it means that you need to rebuild
the `ovirt-engine-nodejs-modules` RPM so that its offline cache directory
contains all dependencies currently required by your project.

== JavaScript dependency management

Simply modify the `projects.list` file, adding URL(s) referencing your
project's `package.json` file and the associated `yarn.lock` file.

Both `package.json` and `yarn.lock` are mandatory. The build will fail
if any of those files are not available.

== Package versioning

When changing the `projects.list` file, bump `.y` in `Version` and reset
the `Release` number.

When rebuilding the package to reflect changes in the consuming projects
(the ones listed in the `projects.list` file), bump `.z` in `Version`
and reset the `Release` number.

As for packaging related changes, simply bump the `Release` number.

== Pre-seed

If you need dependencies to exist in ovirt-engine-nodejs-modules, but
your package.json and yarn.lock files are not yet committed, you can
pre-seed ovirt-engine-nodejs-modules with your files to avoid a
chicken and egg problem.

Add a subdirectory in the pre-seed directory, and in that subdirectory
add copies of the package.json and yarn.lock your new project or patch
is using.

For example:
 - pre-seed/2018-01-14-ovirt-engine-dashboard/package.json
 - pre-seed/2018-01-14-ovirt-engine-dashboard/yarn.lock
 - pre-seed/2018-01-15-example-project/package.json
 - pre-seed/2018-01-15-example-project/yarn.lock

(The pre-seed directory can occasionally be pruned.)

After committing a patch that adds a pre-seed, the newly built version
of ovirt-engine-nodejs-modules will now be pre-seeded with your
new package.json + yarn.lock requirements.
