name: check the PR
on:
  pull_request:

jobs:
  test_el8:
    name: run check.sh to verify content
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8

    steps:
      - name: enable repos and choose module versions
        run: |
          dnf -y copr enable ovirt/ovirt-master-snapshot centos-stream-8
          dnf -y module enable nodejs:14

      - name: install check.sh required packages
        run: |
          dnf -y install git jq wget rpmlint

      # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      - name: checkout sources (PR head, not the PR merge)
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          ref: ${{ github.event.pull_request.head.sha }}

      # The script needs to know the PR base and head commits to be able to look at the
      # contents of the range of commits for the PR. The required spec file must be updated
      # somewhere in one of those commits!
      - name: run automation/check.sh
        run: |
          ./automation/check.sh ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
