name: check the PR
on:
  pull_request:

jobs:
  test_el8:
    name: run check.sh to verify content

    runs-on: ubuntu-latest
    container:
      image: quay.io/ovirt/buildcontainer:el8stream

    env:
      # The check version script needs to know the PR base and head commits to be able to
      # look at the contents of the range of commits for the PR. The required spec file
      # change must be contained somewhere in one of those commits!  This env var will
      # be picked up by the script and used as the range.
      CHECK_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

    steps:
      - name: make sure check.sh required packages are installed
        run: |
          dnf -y install git jq wget rpmlint

      # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      - name: checkout sources (PR head, not the PR merge)
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          ref: ${{ github.event.pull_request.head.sha }}

      - name: run automation/check.sh
        run: |
          ./automation/check.sh
