name: check the PR
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: el8
            container-image: quay.io/ovirt/buildcontainer:el8stream
          - name: el9
            container-image: quay.io/ovirt/buildcontainer:el9stream

    name: ${{ matrix.name }}, run check.sh to verify content
    container:
      image: ${{ matrix.container-image }}

    env:
      # The check version script needs to know the PR base and head commits to be able to
      # look at the contents of the range of commits for the PR. The required spec file
      # change must be contained somewhere in one of those commits!  This env var will
      # be picked up by the script and used as the range.
      CHECK_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

    steps:
      - name: make sure check.sh required packages are installed
        run: |
          dnf -y install git jq wget rpmlint

      - name: checkout sources (PR head, not the PR merge)
        uses: ovirt/checkout-action@main
        with:
          fetch-depth: 20

      - name: run automation/check.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./automation/check.sh
